version: '3.8'

services:
  strapi:
    image: node:18
    container_name: strapi
    ports:
      - "1337:1337"
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build && npm run start"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1337
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
